package com.comp2042.input;

/**
 * Describes the type of input event generated by the player or game thread.
 * <p>
 * These values indicate how the active brick should be manipulated on the board.
 */
public enum EventType {

    /**
     * Move the active brick one row down (gravity or soft drop).
     */
    DOWN,

    /**
     * Move the active brick one column to the left.
     */
    LEFT,

    /**
     * Move the active brick one column to the right.
     */
    RIGHT,

    /**
     * Rotate the active brick.
     */
    ROTATE
}
