package com.comp2042.input;

/**
 * Represents the origin of an input event processed by the game.
 * <p>
 * Events can either be generated directly by the user (keyboard or mouse input)
 * or generated by a background game thread (for example, the automatic
 * gravity tick or other internal updates).
 */
public enum EventSource {

    /**
     * Event triggered directly by the player (keyboard, mouse, scroll, etc.).
     */
    USER,

    /**
     * Event triggered by a background game thread, such as the timer driving
     * automatic brick falling or periodic updates.
     */
    THREAD
}
