package com.comp2042.input;

/**
 * Represents a single movement-related input event sent to the game controller.
 * <p>
 * A {@code MoveEvent} contains both the type of movement requested
 * ({@link EventType}) and the origin of the event ({@link EventSource}).
 * These events are generated either by user interactions (keyboard or mouse)
 * or by background game threads that trigger automatic movements such as gravity.
 */
public final class MoveEvent {
    private final EventType eventType;
    private final EventSource eventSource;

    /**
     * Creates a new movement event with the given type and source.
     *
     * @param eventType   the specific movement requested (e.g., DOWN, LEFT, RIGHT, ROTATE)
     * @param eventSource the origin of the event, such as USER or THREAD
     */
    public MoveEvent(EventType eventType, EventSource eventSource) {
        this.eventType = eventType;
        this.eventSource = eventSource;
    }

    /**
     * Returns the type of movement requested by this event.
     *
     * @return the {@link EventType} describing the movement action
     */
    public EventType getEventType() {
        return eventType;
    }

    /**
     * Returns the origin of this event.
     *
     * @return the {@link EventSource} indicating whether the event was
     *         generated by the user or by a background thread
     */
    public EventSource getEventSource() {
        return eventSource;
    }
}
